switched to new format

diff --git a/.nvidia-ci.yml b/.nvidia-ci.yml
--- a/.nvidia-ci.yml
+++ b/.nvidia-ci.yml
@@ -34,6 +34,7 @@ variables:
   # Define the public staging registry
   STAGING_REGISTRY: ghcr.io/nvidia
   STAGING_VERSION: "${CI_COMMIT_SHORT_SHA}"
+  PUBLISH_VERSIONS: 535.261.03
 
 .image-pull-rules:
   # We delay the job start to allow the public pipeline to generate the required images.
@@ -217,6 +218,18 @@ image-rhel9:
     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
     - !reference [.pipeline-trigger-rules, rules]
 
+.scan-ubuntu20.04:
+  # Repeat for each DRIVER_VERSION
+  extends:
+    - .driver-versions-ubuntu20.04
+    - .scan-generic
+  rules:
+    - !reference [.scan-rules-common, rules]
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
+    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
+    - !reference [.pipeline-trigger-rules, rules]
+
 .scan-ubuntu22.04:
   # Repeat for each DRIVER_VERSION
   extends:
@@ -268,7 +281,7 @@ image-rhel9:
 # Define the scan targets
 scan-ubuntu20.04-amd64:
   extends:
-    - .scan
+    - .scan-ubuntu20.04
     - .dist-ubuntu20.04
     - .platform-amd64
   needs:
@@ -276,7 +289,7 @@ scan-ubuntu20.04-amd64:
 
 scan-ubuntu20.04-arm64:
   extends:
-    - .scan
+    - .scan-ubuntu20.04
     - .dist-ubuntu20.04
     - .platform-arm64
   needs:
@@ -369,19 +382,13 @@ scan-rhel9-arm64:
     OUT_REGISTRY_USER: "${NGC_REGISTRY_USER}"
     OUT_REGISTRY_TOKEN: "${NGC_REGISTRY_TOKEN}"
     OUT_REGISTRY: "${NGC_REGISTRY}"
+    OUT_IMAGE_NAME: "${NGC_STAGING_REGISTRY}/driver"
 
 # Define the external release helpers
 .release:ngc:
   extends:
     - .release:external
     - .release:ngc-variables
-  script:
-    - |
-      if [[ -n "${OUT_VERSION}" ]]; then
-        echo "${CI_COMMIT_SHORT_SHA}-${DRIVER_VERSION}-${DIST} ${OUT_VERSION}-${DRIVER_VERSION}-${OUT_DIST}" > build-info-${DRIVER_VERSION}-${OUT_DIST}.txt
-      else
-        echo "${CI_COMMIT_SHORT_SHA}-${DRIVER_VERSION}-${DIST} ${DRIVER_VERSION}-${OUT_DIST}" > build-info-${DRIVER_VERSION}-${OUT_DIST}.txt
-      fi
 
 release:ngc-ubuntu20.04:
   extends:
@@ -495,139 +502,97 @@ release:ngc-rhel9.6:
   variables:
     OUT_DIST: "rhel9.6"
 
-.process-build-info:
+generate-build-info:
   stage: ngc-publish
-  allow_failure: true
-  script:
-    - |
-      distributions="ubuntu20.04 ubuntu22.04 ubuntu24.04 rhel8 rhcos4.12 rhcos4.13 rhcos4.14 rhcos4.15 rhcos4.16 rhcos4.17 rhcos4.18 rhel8.8 rhel8.10"
-      > combined-build-info.txt
-      for dist in $distributions; do
-        for driver_version in ${DRIVER_VERSIONS}; do
-          if [ -f "build-info-${driver_version}-${dist}.txt" ]; then
-            cat "build-info-${driver_version}-${dist}.txt" >> combined-build-info.txt
-          fi
-        done
-      done
-      # Verify we have data
-      if [ ! -s combined-build-info.txt ]; then
-        echo "Error: No build information was collected"
-        exit 1
-      fi
   artifacts:
     paths:
-      - combined-build-info.txt
+      - build-info/${CI_PIPELINE_ID}-full.txt
+  script:
+    - |
+      > build-info/${CI_PIPELINE_ID}-full.txt
+      for DRIVER_VERSION in ${PUBLISH_VERSIONS}; do
+        for file in build-info/${CI_PIPELINE_ID}-${DRIVER_VERSION}-*; do
+          cat "$file" >> build-info/${CI_PIPELINE_ID}-full.txt
+        done
+      done
+      if [ ! -s "build-info/${CI_PIPELINE_ID}-full.txt" ]; then
+        echo "Error: No build information was collected in the Release jobs"
+        exit 1
+      fi
 
-process-build-info-release:
+.update-nspect:
+  stage: ngc-publish
+  needs:
+    - job: generate-build-info
+      artifacts: true
+  image: 
+    name: "${CNT_NGC_PUBLISH_IMAGE}"
+    pull_policy: always
+  variables:
+    PROJECT_NAME: "driver"
+    REPO_URL: "https://github.com/NVIDIA/gpu-driver-container.git"
+  script:
+    - |
+      cnt-ngc-publish nspect --versions-file "build-info/${CI_PIPELINE_ID}-full.txt"
+
+# Update the nspect staging environment to test the nspect publishing logic
+update-nspect-staging:
   extends:
-    - .process-build-info
+    - .update-nspect
+  except:
+    - tags
+  variables:
+    ENV: "stage"
+    RELEASE_VERSION: "test"
+    NSPECT_CLIENT_ID: "${NSPECT_STAGING_CLIENT_ID}"
+    NSPECT_CLIENT_SECRET: "${NSPECT_STAGING_CLIENT_SECRET}"
+
+# Update the nspect production environment with the new release
+update-nspect:
+  extends:
+    - .update-nspect
   rules:
     - if: $CI_COMMIT_TAG
-  needs:
-    - job: release:ngc-ubuntu20.04
-      optional: true
-    - job: release:ngc-ubuntu22.04
-      optional: true
-    - job: release:ngc-ubuntu24.04
-      optional: true
-    - job: release:ngc-rhel8.8
-      optional: true
-    - job: release:ngc-rhel8.10
-      optional: true
-    - job: release:ngc-rhcos4.12
-      optional: true
-    - job: release:ngc-rhcos4.13
-      optional: true
-    - job: release:ngc-rhcos4.14
-      optional: true
-    - job: release:ngc-rhcos4.15
-      optional: true
-    - job: release:ngc-rhcos4.16
-      optional: true
-    - job: release:ngc-rhcos4.17
-      optional: true
-    - job: release:ngc-rhcos4.18
-      optional: true
+  variables:
+    OSRB_BUG_ID: "${OSRB_BUG_ID}"
+    ENV: "prod"
+    RELEASE_VERSION: "${CI_COMMIT_TAG}"
+    NSPECT_CLIENT_ID: "${NSPECT_PROD_CLIENT_ID}"
+    NSPECT_CLIENT_SECRET: "${NSPECT_PROD_CLIENT_SECRET}"
 
-process-build-info-staging:
-  extends:
-    - .process-build-info
-  needs:
-    - job: release:staging-ubuntu20.04
-      optional: true
-    - job: release:staging-ubuntu22.04
-      optional: true
-    - job: release:staging-ubuntu24.04
-      optional: true
-    - job: release:staging-rhel8
-      optional: true
-
-.raise-merge-request:
+.publish-images:
   stage: ngc-publish
-  image: 
+  image:
     name: "${CNT_NGC_PUBLISH_IMAGE}"
     pull_policy: always
   variables:
     GITLAB_ACCESS_TOKEN: "${CNT_GITLAB_TOKEN}"
   script:
-    - cnt-ngc-publish render --project-name "gpu-driver-container" --versions-file "combined-build-info.txt" --output gpu-driver-container.yaml
+    - cnt-ngc-publish render --project-name "gpu-driver-container" --versions-file "build-info/${CI_PIPELINE_ID}-full.txt" --output gpu-driver-container.yaml
     - cnt-ngc-publish merge-request --files "gpu-driver-container.yaml"
 
-raise-staging-merge-request:
+# Raise an MR to publish the image to NGC
+ngc-image-publish:
   extends:
-    - .raise-merge-request
-  needs:
-    - job: process-build-info-staging
-      artifacts: true
-  before_script:
-    - export NGC_PUBLISHING_PROJECT_PATH="dl/container-dev/ngc-automation"
-
-raise-publishing-merge-request:
-  extends:
-    - .raise-merge-request
+    - .publish-images
   rules:
     - if: $CI_COMMIT_TAG
   needs:
-    - job: process-build-info-release
+    - job: update-nspect
+    - job: generate-build-info
       artifacts: true
-
-.update-nspect:
-  stage: ngc-publish
-  image: 
-    name: "${CNT_NGC_PUBLISH_IMAGE}"
-    pull_policy: always
   variables:
-    PROJECT_NAME: "gpu-driver-container"
-    REPO_URL: "ssh://git@gitlab-master.nvidia.com:12051/dl/container-dev/driver.git"
-  script:
-    - |
-      cnt-ngc-publish nspect --versions-file "combined-build-info.txt"
+    NGC_PUBLISHING_PROJECT_PATH: "${NGC_PUBLISHING_PROD_PROJECT_PATH}"
 
-update-nspect-staging:
-  needs:
-    - job: process-build-info-staging
-      artifacts: true
+# Create a dummy MR that exercises the publishing logic
+mock-image-publish:
   extends:
-    - .update-nspect
-  variables:
-    RELEASE_VERSION: "${CI_COMMIT_SHORT_SHA}"
-    ENV: "stage"
-  before_script:
-    - export NSPECT_CLIENT_ID="${NSPECT_STAGING_CLIENT_ID}"
-    - export NSPECT_CLIENT_SECRET="${NSPECT_STAGING_CLIENT_SECRET}"
-
-update-nspect-publishing:
+    - .publish-images
+  except:
+    - tags
   needs:
-    - job: process-build-info-release
+    - job: update-nspect-staging
+    - job: generate-build-info
       artifacts: true
-  extends:
-    - .update-nspect
-  rules:
-    - if: $CI_COMMIT_TAG
   variables:
-    RELEASE_VERSION: "${CI_COMMIT_TAG}"
-    OSRB_BUG_ID: "${OSRB_ID}"
-    ENV: "prod"
-  before_script:
-    - export NSPECT_CLIENT_ID="${NSPECT_CLIENT_ID}"
-    - export NSPECT_CLIENT_SECRET="${NSPECT_CLIENT_SECRET}"
+    NGC_PUBLISHING_PROJECT_PATH: "${NGC_PUBLISHING_TEST_PROJECT_PATH}"
