Fedora: Improve support for kernel-type including derivation based on driver branch
This is mainly applying changes visible on RHEL build to fedora.

diff --git a/fedora/nvidia-driver b/fedora/nvidia-driver
--- a/fedora/nvidia-driver
+++ b/fedora/nvidia-driver
@@ -16,9 +16,11 @@ NVIDIA_PEERMEM_MODULE_PARAMS=()
 TARGETARCH=${TARGETARCH:?"Missing TARGETARCH env"}
 USE_HOST_MOFED="${USE_HOST_MOFED:-false}"
 DNF_RELEASEVER=${DNF_RELEASEVER:-""}
+KERNEL_MODULE_TYPE=${KERNEL_MODULE_TYPE:-auto}
 
-OPEN_KERNEL_MODULES_ENABLED=${OPEN_KERNEL_MODULES_ENABLED:-false}
-[[ "${OPEN_KERNEL_MODULES_ENABLED}" == "true" ]] && KERNEL_TYPE=kernel-open || KERNEL_TYPE=kernel
+export NVCC_CCBIN='gcc-14'
+# export CC='gcc-14'
+export CC+=" -std=gnu17"
 
 DRIVER_ARCH=${TARGETARCH/amd64/x86_64} && DRIVER_ARCH=${DRIVER_ARCH/arm64/aarch64}
 echo "DRIVER_ARCH is $DRIVER_ARCH"
@@ -563,6 +565,36 @@ _shutdown() {
     return 1
 }
 
+# _resolve_kernel_type determines which kernel module type, open or proprietary, to install.
+# This function assumes that the nvidia-installer binary is in the PATH, so this function
+# should only be invoked after the userspace driver components have been installed.
+#
+# KERNEL_MODULE_TYPE is the frontend interface that users can use to configure which module
+# to install. Valid values for KERNEL_MODULE_TYPE are 'auto' (default), 'open', and 'proprietary'.
+# When 'auto' is configured, we use the nvidia-installer to recommend the module type to install.
+_resolve_kernel_type() {
+  if [ "${KERNEL_MODULE_TYPE}" == "proprietary" ]; then
+    KERNEL_TYPE=kernel
+  elif [ "${KERNEL_MODULE_TYPE}" == "open" ]; then
+    KERNEL_TYPE=kernel-open
+  elif [ "${KERNEL_MODULE_TYPE}" == "auto" ]; then
+    kernel_module_type=$(nvidia-installer --print-recommended-kernel-module-type)
+    if [ $? -ne 0 ]; then
+      echo "failed to retrieve the recommended kernel module type from nvidia-installer, falling back to using the driver branch"
+      _resolve_kernel_type_from_driver_branch
+      return 0
+    fi
+    [[ "${kernel_module_type}" == "open" ]] && KERNEL_TYPE=kernel-open || KERNEL_TYPE=kernel
+  else
+    echo "invalid value for the KERNEL_MODULE_TYPE variable: ${KERNEL_MODULE_TYPE}"
+    return 1
+  fi
+}
+
+_resolve_kernel_type_from_driver_branch() {
+  [[ "${DRIVER_BRANCH}" -lt 560 ]] && KERNEL_TYPE=kernel || KERNEL_TYPE=kernel-open
+}
+
 _find_vgpu_driver_version() {
     local count=""
     local version=""
@@ -629,11 +661,16 @@ _prepare() {
 
     _apply_patch
 
+    # Determine the kernel module type
+    _resolve_kernel_type || exit 1
+
     # Install the userspace components and copy the kernel module sources.
-    sh NVIDIA-Linux-$DRIVER_ARCH-$DRIVER_VERSION${PATCHED_SUFFIX:-}.run -x -m=${KERNEL_TYPE} && \
+    sh NVIDIA-Linux-$DRIVER_ARCH-$DRIVER_VERSION${PATCHED_SUFFIX:-}.run -x -m ${KERNEL_TYPE} && \
         cd NVIDIA-Linux-$DRIVER_ARCH-$DRIVER_VERSION${PATCHED_SUFFIX:-} && \
-        sh /tmp/install.sh nvinstall && \
-        mkdir -p /usr/src/nvidia-$DRIVER_VERSION && \
+        sh /tmp/install.sh nvinstall
+
+    # Copy the kernel module sources
+    mkdir -p /usr/src/nvidia-$DRIVER_VERSION && \
         mv LICENSE mkprecompiled ${KERNEL_TYPE} /usr/src/nvidia-$DRIVER_VERSION && \
         sed '9,${/^\(kernel\|LICENSE\)/!d}' .manifest > /usr/src/nvidia-$DRIVER_VERSION/.manifest
 
@@ -719,15 +756,19 @@ update() {
     fi
     exec 3>&-
 
-    # vgpu driver version is choosen dynamically during runtime, so pre-compile modules for
+    # vgpu driver version is chosen dynamically during runtime, so pre-compile modules for
     # only non-vgpu driver types
     if [ "${DRIVER_TYPE}" != "vgpu" ]; then
-        # Install the userspace components and copy the kernel module sources.
         if [ ! -e /usr/src/nvidia-${DRIVER_VERSION}/mkprecompiled ]; then
-            sh NVIDIA-Linux-$DRIVER_ARCH-$DRIVER_VERSION.run -x -m=${KERNEL_TYPE} && \
+            # Determine the kernel module type
+            _resolve_kernel_type || exit 1
+            # Install the userspace components
+            sh NVIDIA-Linux-$DRIVER_ARCH-$DRIVER_VERSION.run -x -m ${KERNEL_TYPE} && \
                 cd NVIDIA-Linux-$DRIVER_ARCH-$DRIVER_VERSION && \
-                sh /tmp/install.sh nvinstall && \
-                mkdir -p /usr/src/nvidia-$DRIVER_VERSION && \
+                sh /tmp/install.sh nvinstall
+
+            # Copy the kernel module sources
+            mkdir -p /usr/src/nvidia-$DRIVER_VERSION && \
                 mv LICENSE mkprecompiled ${KERNEL_TYPE} /usr/src/nvidia-$DRIVER_VERSION && \
                 sed '9,${/^\(kernel\|LICENSE\)/!d}' .manifest > /usr/src/nvidia-$DRIVER_VERSION/.manifest
         fi
@@ -742,6 +783,8 @@ update() {
     # _resolve_kernel_version || exit 1
     _install_prerequisites
     if _kernel_requires_package; then
+        # ensure KERNEL_TYPE is set before compiling kernel modules
+        [[ -n "${KERNEL_TYPE}" ]] || _resolve_kernel_type || exit 1
         _create_driver_package
     fi
     _remove_prerequisites
