Fix if statement which sets the custom firmware path on the host
Signed-off-by: Christopher Desiniotis <cdesiniotis@nvidia.com>

diff --git a/rhel8/nvidia-driver b/rhel8/nvidia-driver
--- a/rhel8/nvidia-driver
+++ b/rhel8/nvidia-driver
@@ -313,10 +313,10 @@ _load_driver() {
         echo "Configuring the following firmware search path in '$fw_path_config_file': $nv_fw_search_path"
         if [[ ! -z $(grep '[^[:space:]]' $fw_path_config_file) ]]; then
             echo "WARNING: A search path is already configured in $fw_path_config_file"
-
-            echo "         Retaining the current configuration. Note, GSP firmware may not be found and thus won't be used by the NVIDIA driver."
-       fi
-        echo -n "$nv_fw_search_path" > $fw_path_config_file
+            echo "         Retaining the current configuration"
+        else
+            echo -n "$nv_fw_search_path" > $fw_path_config_file || echo "Failed to configure the firmware search path"
+        fi
     fi
 
     echo "Loading ipmi and i2c_core kernel modules..."
