Add support to build/load nvidia-peermem on OCP

diff --git a/rhel8/nvidia-driver b/rhel8/nvidia-driver
--- a/rhel8/nvidia-driver
+++ b/rhel8/nvidia-driver
@@ -11,10 +11,15 @@ NUM_VGPU_DEVICES=0
 NVIDIA_MODULE_PARAMS=()
 NVIDIA_UVM_MODULE_PARAMS=()
 NVIDIA_MODESET_MODULE_PARAMS=()
+NVIDIA_PEERMEM_MODULE_PARAMS=()
 TARGETARCH=${TARGETARCH:?"Missing TARGETARCH env"}
+USE_HOST_MOFED="${USE_HOST_MOFED:-false}"
 
 DRIVER_ARCH=${TARGETARCH/amd64/x86_64} && DRIVER_ARCH=${DRIVER_ARCH/arm64/aarch64}
 echo "DRIVER_ARCH is $DRIVER_ARCH"
+
+SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+source $SCRIPT_DIR/common.sh
 
 _update_package_cache() {
     if [ "${PACKAGE_TAG:-}" != "builtin" ]; then
@@ -169,6 +174,22 @@ _create_driver_package() (
 
     echo "Compiling NVIDIA driver kernel modules..."
     cd /usr/src/nvidia-${DRIVER_VERSION}/kernel
+
+    if _gpu_direct_rdma_enabled; then
+        ln -s /run/mellanox/drivers/usr/src/ofa_kernel /usr/src/
+        # if arch directory exists(MOFED >=5.5) then create a symlink as expected by GPU driver installer
+        # This is required as currently GPU driver installer doesn't expect headers in x86_64 folder, but only in either default or kernel-version folder.
+        # ls -ltr /usr/src/ofa_kernel/
+        # lrwxrwxrwx 1 root root   36 Dec  8 20:10 default -> /etc/alternatives/ofa_kernel_headers
+        # drwxr-xr-x 4 root root 4096 Dec  8 20:14 x86_64
+        # lrwxrwxrwx 1 root root   44 Dec  9 19:05 5.4.0-90-generic -> /usr/src/ofa_kernel/x86_64/5.4.0-90-generic/
+        if [[ -d /run/mellanox/drivers/usr/src/ofa_kernel/x86_64/`uname -r` ]]; then
+            if [[ ! -e /usr/src/ofa_kernel/`uname -r` ]]; then
+                ln -s /run/mellanox/drivers/usr/src/ofa_kernel/x86_64/`uname -r` /usr/src/ofa_kernel/
+            fi
+        fi
+    fi
+
     make -s -j SYSSRC=/lib/modules/${KERNEL_VERSION}/build nv-linux.o nv-modeset-linux.o > /dev/null
 
     echo "Relinking NVIDIA driver kernel modules..."
@@ -250,6 +271,13 @@ _get_module_params() {
        done <"${base_path}/nvidia-modeset.conf"
        echo "Module parameters provided for nvidia-modeset: ${NVIDIA_MODESET_MODULE_PARAMS[@]}"
     fi
+    # nvidia-peermem
+    if [ -f "${base_path}/nvidia-peermem.conf" ]; then
+       while IFS="" read -r param || [ -n "$param" ]; do
+           NVIDIA_PEERMEM_MODULE_PARAMS+=("$param")
+       done <"${base_path}/nvidia-peermem.conf"
+       echo "Module parameters provided for nvidia-peermem: ${NVIDIA_PEERMEM_MODULE_PARAMS[@]}"
+    fi
 }
 
 # Load the kernel modules and start persistenced.
@@ -266,6 +294,13 @@ _load_driver() {
     modprobe nvidia-uvm "${NVIDIA_UVM_MODULE_PARAMS[@]}"
     modprobe nvidia-modeset "${NVIDIA_MODESET_MODULE_PARAMS[@]}"
     set +o xtrace -o nounset
+
+    if _gpu_direct_rdma_enabled; then
+        echo "Loading NVIDIA Peer Memory kernel module..."
+        set -o xtrace +o nounset
+        modprobe -a nvidia-peermem "${NVIDIA_PEERMEM_MODULE_PARAMS[@]}"
+        set +o xtrace -o nounset
+    fi
 
     echo "Starting NVIDIA persistence daemon..."
     nvidia-persistenced --persistence-mode
@@ -299,6 +334,7 @@ _unload_driver() {
     local nvidia_refs=0
     local nvidia_uvm_refs=0
     local nvidia_modeset_refs=0
+    local nvidia_peermem_refs=0
 
     echo "Stopping NVIDIA persistence daemon..."
     if [ -f /var/run/nvidia-persistenced/nvidia-persistenced.pid ]; then
@@ -360,7 +396,12 @@ _unload_driver() {
         nvidia_refs=$(< /sys/module/nvidia/refcnt)
         rmmod_args+=("nvidia")
     fi
-    if [ ${nvidia_refs} -gt ${nvidia_deps} ] || [ ${nvidia_uvm_refs} -gt 0 ] || [ ${nvidia_modeset_refs} -gt 0 ]; then
+    if [ -f /sys/module/nvidia_peermem/refcnt ]; then
+        nvidia_peermem_refs=$(< /sys/module/nvidia_peermem/refcnt)
+        rmmod_args+=("nvidia-peermem")
+        ((++nvidia_deps))
+    fi
+    if [ ${nvidia_refs} -gt ${nvidia_deps} ] || [ ${nvidia_uvm_refs} -gt 0 ] || [ ${nvidia_modeset_refs} -gt 0 ] || [ ${nvidia_peermem_refs} -gt 0 ]; then
         echo "Could not unload NVIDIA driver kernel modules, driver is in use" >&2
         return 1
     fi
@@ -607,6 +648,48 @@ update() {
     exit 0
 }
 
+# Wait for MOFED drivers to be loaded and load nvidia-peermem whenever it gets unloaded during MOFED driver updates
+reload_nvidia_peermem() {
+    if [ "$USE_HOST_MOFED" = "true" ]; then
+        until  lsmod | grep mlx5_core > /dev/null 2>&1 && [ -f /sys/module/nvidia/refcnt ];
+        do
+            echo "waiting for mellanox ofed and nvidia drivers to be installed"
+            sleep 10
+        done
+    else
+        # use driver readiness flag created by MOFED container
+        until  [ -f /run/mellanox/drivers/.driver-ready ] && [ -f /sys/module/nvidia/refcnt ];
+        do
+            echo "waiting for mellanox ofed and nvidia drivers to be installed"
+            sleep 10
+        done
+    fi
+    # get any parameters provided for nvidia-peermem
+    _get_module_params && set +o nounset
+    if chroot /run/nvidia/driver modprobe nvidia-peermem "${NVIDIA_PEERMEM_MODULE_PARAMS[@]}"; then
+        if [ -f /sys/module/nvidia_peermem/refcnt ]; then
+            echo "successfully loaded nvidia-peermem module, now waiting for signal"
+            sleep inf
+            trap "echo 'Caught signal'; exit 1" HUP INT QUIT PIPE TERM
+        fi
+    fi
+    echo "failed to load nvidia-peermem module"
+    exit 1
+}
+
+# probe by gpu-opertor for liveness/startup checks for nvidia-peermem module to be loaded when MOFED drivers are ready
+probe_nvidia_peermem() {
+    if lsmod | grep mlx5_core > /dev/null 2>&1; then
+        if [ ! -f /sys/module/nvidia_peermem/refcnt ]; then
+            echo "nvidia-peermem module is not loaded"
+            return 1
+        fi
+    else
+        echo "MOFED drivers are not ready, skipping probe to avoid container restarts..."
+    fi
+    return 0
+}
+
 usage() {
     cat >&2 <<EOF
 Usage: $0 COMMAND [ARG...]
@@ -629,6 +712,8 @@ case "${command}" in
     build) options=$(getopt -l accept-license,tag: -o a:t -- "$@") ;;
     load) options="" ;;
     update) options=$(getopt -l kernel:,sign:,tag: -o k:s:t: -- "$@") ;;
+    reload_nvidia_peermem) options="" ;;
+    probe_nvidia_peermem) options="" ;;
     *) usage ;;
 esac
 if [ $? -ne 0 ]; then
