Add entrypoints to reload and probe nvidia-peermem module status by gpu-operator

diff --git a/ubuntu20.04/nvidia-driver b/ubuntu20.04/nvidia-driver
--- a/ubuntu20.04/nvidia-driver
+++ b/ubuntu20.04/nvidia-driver
@@ -538,6 +538,37 @@ update() {
     exit 0
 }
 
+# Wait for MOFED drivers to be loaded and load nvidia-peermem whenever it gets unloaded during MOFED driver updates
+reload_nvidia_peermem() {
+    until  grep ib_register_peer_memory_client /proc/kallsyms > /dev/null 2>&1 && [ -f /sys/module/nvidia/refcnt ];
+    do
+        echo "waiting for mellanox ofed and nvidia drivers to be installed"
+        sleep 10
+    done
+    if chroot /run/nvidia/driver modprobe nvidia-peermem; then
+        if [ -f /sys/module/nvidia_peermem/refcnt ]; then
+            echo "successfully loaded nvidia-peermem module, now waiting for signal"
+            sleep inf
+            trap "echo 'Caught signal'; exit 1" HUP INT QUIT PIPE TERM
+        fi
+    fi
+    echo "failed to load nvidia-peermem module"
+    exit 1
+}
+
+# probe by gpu-opertor for liveness/startup checks for nvidia-peermem module to be loaded when MOFED drivers are ready
+probe_nvidia_peermem() {
+    if grep ib_register_peer_memory_client /proc/kallsyms > /dev/null 2>&1; then
+        if [ ! -f /sys/module/nvidia_peermem/refcnt ]; then
+            echo "nvidia-peermem module is not loaded"
+            return 1
+        fi
+    else
+        echo "MOFED drivers are not ready, skipping probe to avoid container restarts..."
+    fi
+    return 0
+}
+
 usage() {
     cat >&2 <<EOF
 Usage: $0 COMMAND [ARG...]
@@ -556,6 +587,8 @@ command=$1; shift
 case "${command}" in
     init) options=$(getopt -l accept-license -o a -- "$@") ;;
     update) options=$(getopt -l kernel:,sign:,tag: -o k:s:t: -- "$@") ;;
+    reload_nvidia_peermem) options="" ;;
+    probe_nvidia_peermem) options="" ;;
     *) usage ;;
 esac
 if [ $? -ne 0 ]; then
