end-to-end  gpu driver testing enhancement
Signed-off-by: shiva kumar <shivaku@nvidia.com>

diff --git a/.github/workflows/ci-precompiled.yaml b/.github/workflows/ci-precompiled.yaml
--- a/.github/workflows/ci-precompiled.yaml
+++ b/.github/workflows/ci-precompiled.yaml
@@ -12,7 +12,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-name: End-to-end tests
+name: Precompiled End-to-end tests
 
 on:
   workflow_run:
@@ -21,9 +21,18 @@ on:
       - completed
     branches:
       - main
+  pull_request:
+    types:
+      - opened
+      - synchronize
+    branches:
+      - precompileddrivervalidation
+  push:
+    branches:
+      - precompileddrivervalidation
 
 jobs:
-  e2e-tests-nvidiadriver:
+  e2e-tests-precompiled-nvidiadriver:
     runs-on: ubuntu-latest
 
     steps:
@@ -36,6 +45,7 @@ jobs:
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
+        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
       with:
         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -55,17 +65,38 @@ jobs:
         echo "COMMIT_SHORT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
         DRIVER_VERSIONS=$(grep '^DRIVER_VERSIONS ?=' versions.mk | awk -F' ?= ' '{print $2}')
         echo "DRIVER_VERSIONS=$DRIVER_VERSIONS" >> $GITHUB_ENV
-        
-    - name: Validate gpu driver
+
+    - name: upgrade kernel
       env:
-        TEST_CASE: "./tests/cases/nvidia-driver.sh"
+        TEST_CASE: "./tests/cases/nvidia-kernel-upgrade.sh"
+        SSH_RETRY: "1"
       run: |
         sudo chmod 644 ${{ github.workspace }}/.cache/key
         echo "${{ secrets.AWS_SSH_KEY }}" > ${private_key} && chmod 400 ${private_key}
         rc=0
         for driver_version in ${DRIVER_VERSIONS}; do
           echo "Running e2e for DRIVER_VERSION=$driver_version"
-          ./tests/ci-run-e2e.sh ${TEST_CASE} ${COMMIT_SHORT_SHA}-${driver_version} || status=$?
+          # SHIVA
+          # ./tests/ci-run-e2e.sh ${TEST_CASE} ${COMMIT_SHORT_SHA}-${driver_version} ${SSH_RETRY} || status=$?
+          ./tests/ci-run-e2e.sh ${TEST_CASE} ${driver_version} ${SSH_RETRY} || status=$?
+          if [ $status -ne 0 ]; then
+            echo "Kernel upgrade failed"
+            rc=$status
+          fi
+        done
+        exit $rc
+    
+    - name: Validate gpu driver
+      env:
+        TEST_CASE: "./tests/cases/nvidia-driver.sh"
+        SSH_RETRY: "0"
+      run: |
+        sudo chmod 644 ${{ github.workspace }}/.cache/key
+        echo "${{ secrets.AWS_SSH_KEY }}" > ${private_key} && chmod 400 ${private_key}
+        rc=0
+        for driver_version in ${DRIVER_VERSIONS}; do
+          echo "Running e2e for DRIVER_VERSION=$driver_version"
+          ./tests/ci-run-e2e.sh ${TEST_CASE} ${COMMIT_SHORT_SHA}-${driver_version} ${SSH_RETRY} || status=$?
           if [ $status -ne 0 ]; then
             echo "e2e validation failed for driver version $driver_version with status $status"
             rc=$status
