Test Not for review holodeck kernel version change
Signed-off-by: shiva kumar <shivaku@nvidia.com>

diff --git a/.github/workflows/precompiled.yaml b/.github/workflows/precompiled.yaml
--- a/.github/workflows/precompiled.yaml
+++ b/.github/workflows/precompiled.yaml
@@ -302,7 +302,7 @@ jobs:
           yq e '.spec.kernel.version = "${{ env.KERNEL_VERSION }}"' -i tests/holodeck_${{ env.DIST }}.yaml
 
       - name: Set up Holodeck
-        uses: NVIDIA/holodeck@v0.2.9
+        uses: NVIDIA/holodeck@v0.2.10
         env:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -353,11 +353,11 @@ jobs:
             # add escape character for space
             TEST_CASE_ARGS=$(printf '%q ' "$TEST_CASE_ARGS")
             IMAGE_PATH="./tests/driver-images-${DRIVER_VERSION}-${KERNEL_VERSION}-${DIST}.tar"
-            ./tests/scripts/remote_retry.sh || status=$?
-            if [ $status -ne 0 ]; then
-              echo "Failed to connect to remote instance"
-              exit $status
-            fi
+            # ./tests/scripts/remote_retry.sh || status=$?
+            # if [ $status -ne 0 ]; then
+            #   echo "Failed to connect to remote instance"
+            #   exit $status
+            # fi
             ./tests/ci-run-e2e.sh "${TEST_CASE}" "${TEST_CASE_ARGS}" ${IMAGE_PATH} || status=$?
             if [ $status -eq 1 ]; then
               echo "e2e validation failed for driver version $DRIVER_VERSION with status $status"
